apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-volume
  labels:
    type: local
spec:
  capacity:
    storage: 20Gİ
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostpath:
    path: "/mnt/data"
