kind: Service
apiVersion: v1
metadata:
  name:  phonebook-service
  labels:
    name:  phonebook-service
spec:
  selector:
    app:  phonebook-app-pod
  type:  NodePort
  ports:
  - port:  80
    targetPort:  80
    nodePort:  30001